// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfR4mKGC9Wrsyyz-IT-WMvWg5OwL06RNo',
    appId: '1:535146731830:web:5c858d4736edafffb93b97',
    messagingSenderId: '535146731830',
    projectId: 'fir-flutter-codelab-ebbfd',
    authDomain: 'fir-flutter-codelab-ebbfd.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ebbfd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuzDbu129WDDWbTRzeZit4Oha4HxzzLjM',
    appId: '1:535146731830:android:19a07dcd92a6091ab93b97',
    messagingSenderId: '535146731830',
    projectId: 'fir-flutter-codelab-ebbfd',
    storageBucket: 'fir-flutter-codelab-ebbfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARmBbEROzqOh1p358xu8VpL_KBzeOVtNY',
    appId: '1:535146731830:ios:c80c46af95f23a07b93b97',
    messagingSenderId: '535146731830',
    projectId: 'fir-flutter-codelab-ebbfd',
    storageBucket: 'fir-flutter-codelab-ebbfd.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARmBbEROzqOh1p358xu8VpL_KBzeOVtNY',
    appId: '1:535146731830:ios:c80c46af95f23a07b93b97',
    messagingSenderId: '535146731830',
    projectId: 'fir-flutter-codelab-ebbfd',
    storageBucket: 'fir-flutter-codelab-ebbfd.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
